version: 0.2

env:
  variables:
    PROJECT_NAME: "demo"
    REPORT_DIR: "security-reports"
    SAST_FILE_REPORT: "bandit-report.json"
    SCA_FILE_REPORT: "dependency-check-report.xml"

phases:
  install:
    commands:
      - echo "Iniciando setup inicial..."
      
      - echo "Creando directorio para reportes" 
      - mkdir -p ${REPORT_DIR}
      
      # Instala pre-commit para chequear validaciones
      #- echo "Instalando pre-commit" 
      #- pip install pre-commit
      
      # Instala pipreqs para generar / actualizar requirements.txt
      #- echo "Instalando pipreqs" 
      #- pip install pipreqs

  pre_build:
    commands:
      - echo "Iniciando pre-condiciones..."
      #- echo "Ejecutando pre-commit como paso de validación en CI"
      #- pre-commit run --all-files

      # Si el proyecto usa un archivo requirements.txt, estas línea no son necesaria.
      #- echo "Actualizando requirements.txt para asegurar que todas las dependencias son escaneadas"
      #- pipreqs --force . 

  build:
    commands:
      - echo "Iniciando análsis de seguridad..."
       
      # --- 1. Static Analysis (SAST) con Bandit (Docker) ---
      - echo "Ejecutando SAST con Bandit via Docker"
      # Usando una sola linea para evitar errores de sintaxis YAML
      - docker run --rm -v "$(pwd)":/src:z ghcr.io/pycqa/bandit/bandit -r /src -f json -o /src/${REPORT_DIR}/${SAST_FILE_REPORT} || true
      
      # --- 2. Software Composition Analysis (SCA) con OWASP Dependency-Check (Docker) ---
      # Se ejecuta OWASP Dependency-Check como usuario root user para solventar problemas de permisos
      - echo "Ejecutando SCA con OWASP Dependency-Check via Docker..."
      - docker pull owasp/dependency-check
      - >
          docker run --rm -u root -v "$(pwd)":/src:z owasp/dependency-check 
          --scan /src/requirements.txt 
          --project "${PROJECT_NAME}" 
          --format XML 
          --out /src/${REPORT_DIR}/${SCA_FILE_REPORT} 
          --enableExperimental
          --nvdApiKey ${NIST_API_KEY}
          
  post_build:
    commands:
      - echo "Iniciando procesamiento de reportes..."
    
      - echo "Contenido de directorio de reportes:"
      - ls ${REPORT_DIR}

      - echo "Verificando conectividad con DefectDojo..."
      # Este comando intentará una conexión rápida, si falla, el pipeline se detendrá aquí
      - curl --head --silent --fail "https://${DD_HOST}/api/v2/" || { echo "No se pudo conectar a DefectDojo. Abortando subida."; exit 1; }
      - echo "Conexión a DefectDojo exitosa."

      - echo "Subiendo reportes a DefectDojo vía API con curl..."
      
      # Sube reporte de Bandit con curl si el archivo existe.
      - |
        if [ -f "${REPORT_DIR}/${SAST_FILE_REPORT}" ]; then
          echo "Subiendo reporte SAST a DefectDojo: '${REPORT_DIR}/${SAST_FILE_REPORT}'"
          curl -k -X POST "https://${DD_HOST}/api/v2/import-scan/" \
            -H "Authorization: Token ${DD_API_KEY}" \
            -F "scan_type=Bandit Scan" \
            -F "test_title=SAST - Bandit" \
            -F "file=@${REPORT_DIR}/${SAST_FILE_REPORT}" \
            -F "engagement=$DD_ENGAGEMENT_ID" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "verified=true" \
            -F "active=true" || echo "Error al subir reporte Bandit"
        fi
      
      # Sube reporte de OWASP Dependency-Check con curl si el archivo existe.
      - |
        if [ -f "${REPORT_DIR}/${SCA_FILE_REPORT}" ]; then
          echo "Subiendo reporte SCA a DefectDojo: '${REPORT_DIR}/${SCA_FILE_REPORT}'"
          curl -k -X POST "https://${DD_HOST}/api/v2/import-scan/" \
            -H "Authorization: Token ${DD_API_KEY}" \
            -F "scan_type=Dependency Check Scan" \
            -F "test_title=SCA - Dependency Check" \
            -F "file=@${REPORT_DIR}/${SCA_FILE_REPORT}" \
            -F "engagement=$DD_ENGAGEMENT_ID" \
            -F "scan_date=$(date +%Y-%m-%d)" \
            -F "verified=true" \
            -F "active=true" || echo "Error al subir reporte Dependency-Check"
        fi

artifacts:
  files:
    - '${REPORT_DIR}/**/*'
  discard-paths: no
